/home/gpuuser7/gpuuser7_a/sandeep/NDD_BERT



Some weights of MainModel were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
12.1
Training model :
Apa panduan langkah demi langkah untuk berinvestasi di pasar saham di India?
404290
Apa panduan langkah demi langkah untuk berinvestasi di pasar saham?
404290
data length 404290
 Mengapa orang Afrika-Amerika begitu cantik?
40430
 Mengapa orang hispanik begitu cantik?
40430
train, val, test datasize 262789 20214 40430
Epoch 1:
	Train loss at 0 steps: 0.7769509553909302
Traceback (most recent call last):
  File "/home/gpuuser7/gpuuser7_a/sandeep/NDD_BERT/train.py", line 316, in <module>
    main()
  File "/home/gpuuser7/gpuuser7_a/sandeep/NDD_BERT/train.py", line 261, in main
    train(model, train_dataloader, optimizer, device)
  File "/home/gpuuser7/gpuuser7_a/sandeep/NDD_BERT/train.py", line 83, in train
    loss_main, main_prob = model(input_ids=input_ids, attention_mask=mask, token_type_ids = token_type_ids, labels=targets,device = device)
  File "/home/gpuuser7/gpuuser7_a/miniconda3/envs/sai_sandeep/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/gpuuser7/gpuuser7_a/miniconda3/envs/sai_sandeep/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/gpuuser7/gpuuser7_a/sandeep/NDD_BERT/train.py", line 55, in forward
    output = self.bert(input_ids, attention_mask=attention_mask, token_type_ids=token_type_ids)
  File "/home/gpuuser7/gpuuser7_a/miniconda3/envs/sai_sandeep/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/gpuuser7/gpuuser7_a/miniconda3/envs/sai_sandeep/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/gpuuser7/gpuuser7_a/miniconda3/envs/sai_sandeep/lib/python3.10/site-packages/transformers/models/bert/modeling_bert.py", line 1078, in forward
    embedding_output = self.embeddings(
  File "/home/gpuuser7/gpuuser7_a/miniconda3/envs/sai_sandeep/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/gpuuser7/gpuuser7_a/miniconda3/envs/sai_sandeep/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/gpuuser7/gpuuser7_a/miniconda3/envs/sai_sandeep/lib/python3.10/site-packages/transformers/models/bert/modeling_bert.py", line 217, in forward
    embeddings += position_embeddings
RuntimeError: The size of tensor a (558) must match the size of tensor b (512) at non-singleton dimension 1
