Processing model 1...
Execution completed in 11.96s
Completed processing for model 1
------------------------------
Processing model 2...
Execution completed in 12.98s
Completed processing for model 2
------------------------------
Processing model 3...
Execution completed in 12.17s
Completed processing for model 3
------------------------------
Processing model 4...
Execution completed in 12.14s
Completed processing for model 4
------------------------------
Processing model 5...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/gpuuser1/gpuuser1_a/miniconda3/envs/sai_sandeep/lib/python3.10/site-packages/numpy/lib/npyio.py", line 1373, in loadtxt
    arr = _read(fname, dtype=dtype, comment=comment, delimiter=delimiter,
  File "/home/gpuuser1/gpuuser1_a/miniconda3/envs/sai_sandeep/lib/python3.10/site-packages/numpy/lib/npyio.py", line 1016, in _read
    arr = _load_from_filelike(
ValueError: the number of columns changed from 600 to 181 at row 403287; use `usecols` to select a subset and avoid this error
Traceback (most recent call last):
  File "/home/gpuuser1/gpuuser1_a/sandeep/sandeep/nli/Neighbourhood quality/KNN_learning-opt.py", line 84, in <module>
    main()
  File "/home/gpuuser1/gpuuser1_a/sandeep/sandeep/nli/Neighbourhood quality/KNN_learning-opt.py", line 33, in main
    train_embeddings = read_data(args.input_file_train)
  File "/home/gpuuser1/gpuuser1_a/sandeep/sandeep/nli/Neighbourhood quality/KNN_learning-opt.py", line 14, in read_data
    return np.load(filename).astype(np.float32)
  File "/home/gpuuser1/gpuuser1_a/miniconda3/envs/sai_sandeep/lib/python3.10/site-packages/numpy/lib/npyio.py", line 427, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'embeddings.npy'
embeddings.npy not found for model 5. Skipping cleanup.
Completed processing for model 5
------------------------------
All models processed!
